<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProdukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * INSERT INTO `produk` (`id_produk`, `id_kategori`, `id_penitip`, `id_resep`, `nama_produk`, `deskripsi_produk`, `harga_produk`, `stok_produk`) VALUES
     *(1, 1, NULL, 1, 'Lapis Legit', 'Lapis Legit adalah kue tradisional Indonesia yang terbuat dari lapisan-lapisan tipis yang disusun secara bertahap. Kue ini memiliki tekstur yang lembut dan cita rasa yang kaya akan rempah-rempah. Cocok disajikan sebagai hidangan penutup di berbagai acara spesial atau sebagai camilan santai di waktu senggang.', 850000, 0),
     *(2, 1, NULL, 1, 'Lapis Legit 1/2', 'Lapis Legit adalah kue tradisional Indonesia yang terbuat dari lapisan-lapisan tipis yang disusun secara bertahap. Kue ini memiliki tekstur yang lembut dan cita rasa yang kaya akan rempah-rempah. Cocok disajikan sebagai hidangan penutup di berbagai acara spesial atau sebagai camilan santai di waktu senggang.', 450000, 0),
     *(3, 1, NULL, 2, 'Lapis Surabaya', 'Lapis Surabaya adalah salah satu kue legendaris Indonesia yang terkenal akan lapisan-lapisan warnanya yang cantik. Kue ini terdiri dari lapisan sponge cake berwarna kuning dan cokelat yang diapit dengan selai atau krim di antara setiap lapisannya. Rasanya lembut dan manis, cocok untuk dinikmati bersama secangkir teh atau kopi.', 550000, 0),
     *(4, 1, NULL, 2, 'Lapis Surabaya 1/2', 'Lapis Surabaya adalah salah satu kue legendaris Indonesia yang terkenal akan lapisan-lapisan warnanya yang cantik. Kue ini terdiri dari lapisan sponge cake berwarna kuning dan cokelat yang diapit dengan selai atau krim di antara setiap lapisannya. Rasanya lembut dan manis, cocok untuk dinikmati bersama secangkir teh atau kopi.', 300000, 0),
     *(5, 1, NULL, 3, 'Brownies', 'Brownies adalah kue cokelat yang terkenal di seluruh dunia karena teksturnya yang padat namun lembut dan rasa cokelat yang khas. Biasanya disajikan dalam bentuk persegi atau persegi panjang, brownies merupakan pilihan yang sempurna untuk dinikmati sebagai camilan di siang hari atau sebagai hidangan penutup setelah makan malam.', 250000, 0),
     *(6, 1, NULL, 3, 'Brownies 1/2', 'Brownies adalah kue cokelat yang terkenal di seluruh dunia karena teksturnya yang padat namun lembut dan rasa cokelat yang khas. Biasanya disajikan dalam bentuk persegi atau persegi panjang, brownies merupakan pilihan yang sempurna untuk dinikmati sebagai camilan di siang hari atau sebagai hidangan penutup setelah makan malam.', 150000, 0),
     *(7, 1, NULL, 4, 'Mandarin', 'Mandarin adalah buah jeruk kecil yang memiliki rasa segar dan manis. Buah ini kaya akan vitamin C dan serat, sehingga baik untuk kesehatan tubuh. Mandarin dapat dimakan langsung atau dijadikan tambahan dalam salad buah, kue, atau minuman.', 450000, 0),
     *(8, 1, NULL, 4, 'Mandarin 1/2', 'Mandarin adalah buah jeruk kecil yang memiliki rasa segar dan manis. Buah ini kaya akan vitamin C dan serat, sehingga baik untuk kesehatan tubuh. Mandarin dapat dimakan langsung atau dijadikan tambahan dalam salad buah, kue, atau minuman.', 250000, 0),
     *(9, 1, NULL, 5, 'Spioke', 'Spikoe adalah kue tradisional Indonesia yang terbuat dari bahan-bahan sederhana seperti tepung terigu, gula, telur, dan mentega. Kue ini memiliki tekstur yang renyah di bagian luar dan lembut di bagian dalamnya. Rasanya yang manis membuatnya menjadi camilan favorit di berbagai kesempatan.', 350000, 0),
     *(10, 1, NULL, 5, 'Spioke 1/2', 'Spikoe adalah kue tradisional Indonesia yang terbuat dari bahan-bahan sederhana seperti tepung terigu, gula, telur, dan mentega. Kue ini memiliki tekstur yang renyah di bagian luar dan lembut di bagian dalamnya. Rasanya yang manis membuatnya menjadi camilan favorit di berbagai kesempatan.', 200000, 0),
     *(11, 2, NULL, 6, 'Roti Sosis', 'Roti Sosis adalah roti yang diisi dengan sosis yang biasanya telah dimasak sebelumnya. Roti ini memiliki tekstur yang lembut dan rasa yang gurih dari sosis di dalamnya. Cocok dinikmati sebagai sarapan atau camilan di tengah hari.', 180000, 0),
     *(12, 2, NULL, 7, 'Milk Bun', 'Milk Bun adalah roti lembut yang diperkaya dengan susu sehingga memiliki aroma dan rasa yang lezat. Roti ini sering kali diisi dengan berbagai macam selai atau krim, menjadikannya pilihan yang sempurna untuk camilan ringan atau sarapan yang menyenangkan.', 120000, 0),
     *(13, 2, NULL, 8, 'Roti Keju', 'Roti Keju adalah roti yang diisi dengan keju yang leleh di dalamnya. Roti ini memiliki tekstur yang lembut dan gurih, dengan aroma wangi dari kejunya. Cocok dinikmati saat hangat sebagai camilan atau sarapan yang menggugah selera.', 150000, 0),
     *(14, 3, NULL, 9, 'Choco Creamy Latte', 'Choco Creamy Latte adalah minuman kopi yang disajikan dengan campuran cokelat dan susu. Minuman ini memiliki rasa yang kaya dan creamy dengan sentuhan manis dari cokelat. Cocok dinikmati sebagai minuman penyegar di pagi atau sore hari.', 75000, 0),
     *(15, 3, NULL, 10, 'Matcha Creamy Latte', 'Matcha Creamy Latte adalah minuman kopi yang disajikan dengan campuran bubuk matcha dan susu. Minuman ini memiliki rasa yang unik dengan kombinasi antara pahit dan manis, serta aroma wangi dari matcha. Cocok dinikmati sebagai minuman penenang atau penyemangat di berbagai kesempatan.', 100000, 0),
     *(16, 4, 1, NULL, 'Keripik Kentang 250 gr', 'Keripik Kentang adalah camilan yang populer dan nikmat untuk dinikmati di berbagai kesempatan. Dibuat dari irisan kentang tipis yang digoreng hingga renyah dan garing. Cocok sebagai camilan ringan untuk menemani waktu santai Anda.', 75000, 0),
     *(17, 4, 2, NULL, 'Kopi Luwak Bubuk 250 gr', 'Kopi Luwak merupakan salah satu jenis kopi yang paling terkenal dan mahal di dunia. Kopi ini dikenal karena diproses melalui pencernaan musang luwak, memberikan cita rasa yang unik dan kaya. Dikemas dalam bentuk bubuk siap saji, siap untuk diseduh dan dinikmati kapan pun Anda menginginkannya.', 250000, 0),
     *(18, 4, 3, NULL, 'Matcha Organik Bubuk 100 gr', 'Matcha Organik adalah bubuk teh hijau Jepang yang terkenal akan kelembutan dan kekhasan rasanya. Diproduksi dari daun teh yang digiling halus, matcha memiliki aroma yang segar dan rasa yang khas. Cocok untuk disajikan sebagai minuman atau digunakan sebagai bahan dalam berbagai resep makanan dan minuman.', 300000, 0),
     *(19, 4, 4, NULL, 'Chocolate Bar 100 gr', 'Chocolate Bar adalah sepotong cokelat murni dengan berat 100 gram. Dibuat dari biji kakao berkualitas tinggi, cokelat ini memiliki cita rasa yang lezat dan lembut. Cocok untuk dinikmati sebagai camilan di tengah hari atau sebagai hadiah spesial bagi pecinta cokelat.', 120000, 0);

     */
    public function run(): void
    {
        //DB::table('produk')->delete();
        DB::table('produk')->insert(
            [
                ['id_produk' => 1, 'id_kategori' => 1, 'id_penitip' => NULL, 'id_resep' => 1, 'nama_produk' => 'Lapis Legit', 'foto_produk' => 'produk/lapis-legit.jpg', 'deskripsi_produk' => 'Lapis Legit adalah kue tradisional Indonesia yang terbuat dari lapisan-lapisan tipis yang disusun secara bertahap. Kue ini memiliki tekstur yang lembut dan cita rasa yang kaya akan rempah-rempah. Cocok disajikan sebagai hidangan penutup di berbagai acara spesial atau sebagai camilan santai di waktu senggang.', 'harga_produk' => 850000, 'stok_produk' => 0, 'created_at' => now(), 'updated_at' => now()],
                ['id_produk' => 2, 'id_kategori' => 1, 'id_penitip' => NULL, 'id_resep' => 1, 'nama_produk' => 'Lapis Legit 1/2', 'foto_produk' => 'produk/lapis-legit-12.jpg', 'deskripsi_produk' => 'Lapis Legit adalah kue tradisional Indonesia yang terbuat dari lapisan-lapisan tipis yang disusun secara bertahap. Kue ini memiliki tekstur yang lembut dan cita rasa yang kaya akan rempah-rempah. Cocok disajikan sebagai hidangan penutup di berbagai acara spesial atau sebagai camilan santai di waktu senggang.', 'harga_produk' => 450000, 'stok_produk' => 0, 'created_at' => now(), 'updated_at' => now()],
                ['id_produk' => 3, 'id_kategori' => 1, 'id_penitip' => NULL, 'id_resep' => 2, 'nama_produk' => 'Lapis Surabaya', 'foto_produk' => 'produk/lapis-surabaya.jpg', 'deskripsi_produk' => 'Lapis Surabaya adalah salah satu kue legendaris Indonesia yang terkenal akan lapisan-lapisan warnanya yang cantik. Kue ini terdiri dari lapisan sponge cake berwarna kuning dan cokelat yang diapit dengan selai atau krim di antara setiap lapisannya. Rasanya lembut dan manis, cocok untuk dinikmati bersama secangkir teh atau kopi.', 'harga_produk' => 550000, 'stok_produk' => 0, 'created_at' => now(), 'updated_at' => now()],
                ['id_produk' => 4, 'id_kategori' => 1, 'id_penitip' => NULL, 'id_resep' => 2, 'nama_produk' => 'Lapis Surabaya 1/2', 'foto_produk' => 'produk/lapis-surabaya-12.jpg', 'deskripsi_produk' => 'Lapis Surabaya adalah salah satu kue legendaris Indonesia yang terkenal akan lapisan-lapisan warnanya yang cantik. Kue ini terdiri dari lapisan sponge cake berwarna kuning dan cokelat yang diapit dengan selai atau krim di antara setiap lapisannya. Rasanya lembut dan manis, cocok untuk dinikmati bersama secangkir teh atau kopi.', 'harga_produk' => 300000, 'stok_produk' => 0, 'created_at' => now(), 'updated_at' => now()],
                ['id_produk' => 5, 'id_kategori' => 1, 'id_penitip' => NULL, 'id_resep' => 3, 'nama_produk' => 'Brownies', 'foto_produk' => 'produk/brownies.png', 'deskripsi_produk' => 'Brownies adalah kue cokelat yang terkenal di seluruh dunia karena teksturnya yang padat namun lembut dan rasa cokelat yang khas. Biasanya disajikan dalam bentuk persegi atau persegi panjang, brownies merupakan pilihan yang sempurna untuk dinikmati sebagai camilan di siang hari atau sebagai hidangan penutup setelah makan malam.', 'harga_produk' => 250000, 'stok_produk' => 0, 'created_at' => now(), 'updated_at' => now()],
                ['id_produk' => 6, 'id_kategori' => 1, 'id_penitip' => NULL, 'id_resep' => 3, 'nama_produk' => 'Brownies 1/2', 'foto_produk' => 'produk/brownies-12.png', 'deskripsi_produk' => 'Brownies adalah kue cokelat yang terkenal di seluruh dunia karena teksturnya yang padat namun lembut dan rasa cokelat yang khas. Biasanya disajikan dalam bentuk persegi atau persegi panjang, brownies merupakan pilihan yang sempurna untuk dinikmati sebagai camilan di siang hari atau sebagai hidangan penutup setelah makan malam.', 'harga_produk' => 150000, 'stok_produk' => 0, 'created_at' => now(), 'updated_at' => now()],
                ['id_produk' => 7, 'id_kategori' => 1, 'id_penitip' => NULL, 'id_resep' => 4, 'nama_produk' => 'Mandarin', 'foto_produk' => 'produk/mandarin.jpg', 'deskripsi_produk' => 'Mandarin adalah buah jeruk kecil yang memiliki rasa segar dan manis. Buah ini kaya akan vitamin C dan serat, sehingga baik untuk kesehatan tubuh. Mandarin dapat dimakan langsung atau dijadikan tambahan dalam salad buah, kue, atau minuman.', 'harga_produk' => 450000, 'stok_produk' => 0, 'created_at' => now(), 'updated_at' => now()],
                ['id_produk' => 8, 'id_kategori' => 1, 'id_penitip' => NULL, 'id_resep' => 4, 'nama_produk' => 'Mandarin 1/2', 'foto_produk' => 'produk/mandarin-12.jpg', 'deskripsi_produk' => 'Mandarin adalah buah jeruk kecil yang memiliki rasa segar dan manis. Buah ini kaya akan vitamin C dan serat, sehingga baik untuk kesehatan tubuh. Mandarin dapat dimakan langsung atau dijadikan tambahan dalam salad buah, kue, atau minuman.', 'harga_produk' => 250000, 'stok_produk' => 0, 'created_at' => now(), 'updated_at' => now()],
                ['id_produk' => 9, 'id_kategori' => 1, 'id_penitip' => NULL, 'id_resep' => 5, 'nama_produk' => 'Spioke', 'foto_produk' => 'produk/spioke.jpg', 'deskripsi_produk' => 'Spikoe adalah kue tradisional Indonesia yang terbuat dari bahan-bahan sederhana seperti tepung terigu, gula, telur, dan mentega. Kue ini memiliki tekstur yang renyah di bagian luar dan lembut di bagian dalam nya. Rasanya yang manis membuatnya menjadi camilan favorit di berbagai kesempatan.', 'harga_produk' => 350000, 'stok_produk' => 0, 'created_at' => now(), 'updated_at' => now()],
                ['id_produk' => 10, 'id_kategori' => 1, 'id_penitip' => NULL, 'id_resep' => 5, 'nama_produk' => 'Spioke 1/2', 'foto_produk' => 'produk/spioke-12.jpg', 'deskripsi_produk' => 'Spikoe adalah kue tradisional Indonesia yang terbuat dari bahan-bahan sederhana seperti tepung terigu, gula, telur, dan mentega. Kue ini memiliki tekstur yang renyah di bagian luar dan lembut di bagian dalam nya. Rasanya yang manis membuatnya menjadi camilan favorit di berbagai kesempatan.', 'harga_produk' => 200000, 'stok_produk' => 0, 'created_at' => now(), 'updated_at' => now()],
                ['id_produk' => 11, 'id_kategori' => 2, 'id_penitip' => NULL, 'id_resep' => 6, 'nama_produk' => 'Roti Sosis', 'foto_produk' => 'produk/roti-sosis.jpg', 'deskripsi_produk' => 'Roti Sosis adalah roti yang diisi dengan sosis yang biasanya telah dimasak sebelumnya. Roti ini memiliki tekstur yang lembut dan rasa yang gurih dari sosis di dalamnya. Cocok dinikmati sebagai sarapan atau camilan di tengah hari.', 'harga_produk' => 180000, 'stok_produk' => 0, 'created_at' => now(), 'updated_at' => now()],
                ['id_produk' => 12, 'id_kategori' => 2, 'id_penitip' => NULL, 'id_resep' => 7, 'nama_produk' => 'Milk Bun', 'foto_produk' => 'produk/milk-bun.jpg', 'deskripsi_produk' => 'Milk Bun adalah roti lembut yang diperkaya dengan susu sehingga memiliki aroma dan rasa yang lezat. Roti ini sering kali diisi dengan berbagai macam selai atau krim, menjadikannya pilihan yang sempurna untuk camilan ringan atau sarapan yang menyenangkan.', 'harga_produk' => 120000, 'stok_produk' => 0, 'created_at' => now(), 'updated_at' => now()],
                ['id_produk' => 13, 'id_kategori' => 2, 'id_penitip' => NULL, 'id_resep' => 8, 'nama_produk' => 'Roti Keju', 'foto_produk' => 'produk/roti-keju.jpg', 'deskripsi_produk' => 'Roti Keju adalah roti yang diisi dengan keju yang leleh di dalamnya. Roti ini memiliki tekstur yang lembut dan gurih, dengan aroma wangi dari kejunya. Cocok dinikmati saat hangat sebagai camilan atau sarapan yang menggugah selera.', 'harga_produk' => 150000, 'stok_produk' => 0, 'created_at' => now(), 'updated_at' => now()],
                ['id_produk' => 14, 'id_kategori' => 3, 'id_penitip' => NULL, 'id_resep' => 9, 'nama_produk' => 'Choco Creamy Latte', 'foto_produk' => 'produk/choco-creamy-latte.jpg', 'deskripsi_produk' => 'Choco Creamy Latte adalah minuman kopi yang disajikan dengan campuran cokelat dan susu. Minuman ini memiliki rasa yang kaya dan creamy dengan sentuhan manis dari cokelat. Cocok dinikmati sebagai minuman penyegar di pagi atau sore hari.', 'harga_produk' => 75000, 'stok_produk' => 0, 'created_at' => now(), 'updated_at' => now()],
                ['id_produk' => 15, 'id_kategori' => 3, 'id_penitip' => NULL, 'id_resep' => 10, 'nama_produk' => 'Matcha Creamy Latte', 'foto_produk' => 'produk/matcha-creamy-latte.jpg', 'deskripsi_produk' => 'Matcha Creamy Latte adalah minuman kopi yang disajikan dengan campuran bubuk matcha dan susu. Minuman ini memiliki rasa yang unik dengan kombinasi antara pahit dan manis, serta aroma wangi dari matcha. Cocok dinikmati sebagai minuman penenang atau penyemangat di berbagai kesempatan.', 'harga_produk' => 100000, 'stok_produk' => 0, 'created_at' => now(), 'updated_at' => now()],
                ['id_produk' => 16, 'id_kategori' => 4, 'id_penitip' => 1, 'id_resep' => NULL, 'nama_produk' => 'Keripik Kentang 250 gr', 'foto_produk' => 'produk/keripik-kentang-250-gr.jpg', 'deskripsi_produk' => 'Keripik Kentang adalah camilan yang populer dan nikmat untuk dinikmati di berbagai kesempatan. Dibuat dari irisan kentang tipis yang digoreng hingga renyah dan garing. Cocok sebagai camilan ringan untuk menemani waktu santai Anda.', 'harga_produk' => 75000, 'stok_produk' => 0, 'created_at' => now(), 'updated_at' => now()],
                ['id_produk' => 17, 'id_kategori' => 4, 'id_penitip' => 2, 'id_resep' => NULL, 'nama_produk' => 'Kopi Luwak Bubuk 250 gr', 'foto_produk' => 'produk/kopi-luwak-bubuk-250-gr.jpg', 'deskripsi_produk' => 'Kopi Luwak merupakan salah satu jenis kopi yang paling terkenal dan mahal di dunia. Kopi ini dikenal karena diproses melalui pencernaan musang luwak, memberikan cita rasa yang unik dan kaya. Dikemas dalam bentuk bubuk siap saji, siap untuk diseduh dan dinikmati kapan pun Anda menginginkannya.', 'harga_produk' => 250000, 'stok_produk' => 0, 'created_at' => now(), 'updated_at' => now()],
                ['id_produk' => 18, 'id_kategori' => 4, 'id_penitip' => 3, 'id_resep' => NULL, 'nama_produk' => 'Matcha Organik Bubuk 100 gr', 'foto_produk' => 'produk/matcha-organik-bubuk-100-gr.jpg', 'deskripsi_produk' => 'Matcha Organik adalah bubuk teh hijau Jepang yang terkenal akan kelembutan dan kekhasan rasanya. Diproduksi dari daun teh yang digiling halus, matcha memiliki aroma yang segar dan rasa yang khas. Cocok untuk disajikan sebagai minuman atau digunakan sebagai bahan dalam berbagai resep makanan dan minuman.', 'harga_produk' => 300000, 'stok_produk' => 0, 'created_at' => now(), 'updated_at' => now()],
                ['id_produk' => 19, 'id_kategori' => 4, 'id_penitip' => 4, 'id_resep' => NULL, 'nama_produk' => 'Chocolate Bar 100 gr', 'foto_produk' => 'produk/chocolate-bar-100-gr.jpg', 'deskripsi_produk' => 'Chocolate Bar adalah sepotong cokelat murni dengan berat 100 gram. Dibuat dari biji kakao berkualitas tinggi, cokelat ini memiliki cita rasa yang lezat dan lembut. Cocok untuk dinikmati sebagai camilan di tengah hari atau sebagai hadiah spesial bagi pecinta cokelat.', 'harga_produk' => 120000, 'stok_produk' => 0, 'created_at' => now(), 'updated_at' => now()]
            ]
        );
    }
}
